import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>UX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl">hello</div>
    </>
  );
};

export default Home;
